### ISSUE TITLE
kube-backup fail with "can not export service account secrets"

### ISSUE THREAD

**Issue by peelandsee** [pieterlange/kube-backup#22]
hi!

I'm facing the following issue running kube-backup.
I enabled secrets backup (and properly configured gpg).

It seems kube-backup is unable to extract some secretes of kind `kubernetes.io/service-account-token`

I also tried to upgrade kubectl in kube-system to latest 1.9.2 with no luck.

Our k8s cluster is updated, 1.9.2

I removed the content of "ca.crt" and "token" from the attached log (keeping only first/last chars).

```
[blaine-prod] Exporting resources: secrets
The Secret "default-token-hmg6k" is invalid: type: Invalid value: core.Secret{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"default-token-hmg6k", GenerateName:"", Namespace:"", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string{"kubernetes.io/service-account.name":"default", "kubernetes.io/service-account.uid":"c39f3d03-f623-11e7-bb88-005056970681"}, OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:""}, Data:map[string][]uint8{"ca.crt":[]uint8{0x2d, 0xa}, "namespace":[]uint8{0x62, 0x6c, 0x61, 0x69, 0x6e, 0x65, 0x2d, 0x70, 0x72, 0x6f, 0x64}, "token":[]uint8{0x65, 0x41}}, Type:"kubernetes.io/service-account-token"}: can not export service account secrets
Traceback (most recent call last):
  File "&lt;string&gt;", line 1, in &lt;module&gt;
  File "/usr/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

thanks for your repo!

**Comment by pieterlange** [comment]
Ah, we'll just have to filter those.. i'll patch this soon (tm). There's no point in saving service account secrets as they're automatically rotated.

**Comment by pieterlange** [comment]
Fixed in https://github.com/pieterlange/kube-backup/releases/tag/1.9.3

**Comment by ykfq** [comment]
I think its not a good idea to skip this kind of Secret. When its Secret, use this command to drop the `metadata` key:
```bash
kubectl get secret -o json default-token-tz2wj | jq 'del(.metadata)'
```
